#!/bin/bash
set -x
{% set d_port = salt['pillar.get']('docker:port','2375')%}
{% set s_port = salt['pillar.get']('docker:swarm:port','4000')%}
{% set kv_port = salt['pillar.get']('docker:kv:port','8500')%}

{% if salt['grains.get']('role', 'null') == 'manager' %}

  docker run -d -p {{ kv_port }}:{{ kv_port }} \
    progrium/consul -server -bootstrap

  sleep 5;

  docker run -d -p {{ s_port }}:{{ s_port }} swarm manage \
  -H :{{ s_port }} --replication \
  --advertise {{salt['grains.get']('id')}}:{{ s_port }} \
  consul://{{salt['grains.get']('id')}}:{{ kv_port }}

{% else %}
  sleep 30;
  docker run -d swarm join \
  --advertise={{salt['grains.get']('id')}}:{{ d_port }} \
{% for manager, addrs in salt['mine.get']('role:manager', 'network.interfaces', expr_form='grain').items() %} \
  consul://{{ manager }}:{{ kv_port }} \
{% endfor %} 
{% endif %}
